blank_issues_enabled: false
contact_links:
  - name: ⁉️ Need help with Sarmaterm?
    url: https://github.com/sarmaterm/sarmaterm/discussions
    about: Please start a discussion before opening a bug.
